# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scandlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import bt
import asyncio # 비동기화 모듈

class Ui_Dialog(object):
    def __init__(self):
        self.ar = []
        self.bta = bt.BT()
        self.loop = asyncio.get_event_loop()
        self.dlg = None
        self.filtertxt = None
        self.filtercheck = False

    def setupUi(self, Dialog):
        self.dlg = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 443)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())  
        Dialog.setSizePolicy(sizePolicy)      
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(1, 1, 591, 441))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")

        self.listView = QtWidgets.QListView(self.widget)
        self.listView.setMaximumSize(QtCore.QSize(599, 380))
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 0, 1, 4)
        self.scanBtn = QtWidgets.QPushButton(self.widget)
        self.scanBtn.setObjectName("scanBtn")
        self.scanBtn.clicked.connect(self.clickedScanBtn)
        self.gridLayout.addWidget(self.scanBtn, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.checkBox.stateChanged.connect(self.checkboxFilter)
        self.gridLayout.addWidget(self.checkBox, 1, 2, 1, 1)

        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        
        self.gridLayout.addWidget(self.buttonBox, 1, 3, 1, 1)        
        
        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.lineEdit.textChanged.connect(self.changetext)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.scanBtn.setText(_translate("Dialog", "Scan"))
        self.checkBox.setText(_translate("Dialog", "Filtering"))

    def changetext(self) :
        self.filtertxt = self.lineEdit.text()

    def insertList(self) :
        #Listview에 데이터 넣기
        model = QtGui.QStandardItemModel() # Model 생성
        for l in self.ar:  # Model에 ar에 있는 데이터를 모두 추가   
            item = QtGui.QStandardItem("\t- ".join(l))
            if self.filtercheck :
                if any(self.filtertxt in s for s in l) :
                    model.appendRow(item)
            else :
                model.appendRow(item)
        self.listView.setModel(model)  # listview에 만들어진 Model을 설정            

    def checkboxFilter(self, bcheck) :
        self.filtercheck = bcheck
        self.insertList()

    def clickedScanBtn(self) :
        print("Clicked")
        _translate = QtCore.QCoreApplication.translate
        self.dlg.setWindowTitle(_translate("Dialog", "Dialog - scanning"))
        self.ar.clear()
        self.loop.run_until_complete(self.bta.scan(self.ar))
        self.insertList()
        self.dlg.setWindowTitle(_translate("Dialog", "Dialog"))

